### ISSUE TITLE
Other radix

### ISSUE THREAD

**Issue by cup** [mellowcandle/bitwise#14]
POSIX C also offers Radix 64

although a different implementation might be better, as

`l64a` accepts big-endian integers but outputs little-endian strings.

https://pubs.opengroup.org/onlinepubs/9699919799/functions/l64a.html

**Comment by mellowcandle** [comment]
Any use case for using that ? never heard of it.

**Comment by cup** [comment]
I can be useful for encoding larger numbers

for example, YouTube uses it with its video IDs

**Comment by mellowcandle** [comment]
Interesting, where would you find it useful in bitwise, in the command line ?

**Comment by cup** [comment]
for informational purposes, it could be useful to see a number represent in decimal, binary, hex, and radix-64. to compare and make decisions based on the output
