### ISSUE TITLE
Issues with size calculation

### ISSUE THREAD

**Issue by ioztelcan** [mellowcandle/bitwise#25]
I haven't tested out vigorously but it looks like the size calculation has some problems, at least for small values.

E.g:
```
$ bitwise 369
Decimal: 369
Hexdecimal: 0x171
Octal: 0561
Size: 369bytes
ASCII: .......q
Binary:
0 0 0 0 0 0 0 1 | 0 1 1 1 0 0 0 1 
    15 -  8            7 -  0      
```
or 
```
Decimal: 9
Hexdecimal: 0x9
Octal: 011
Size: 9bytes
ASCII: ........
Binary:
0 0 0 0 1 0 0 1
```

Best,
Ilker

**Comment by mellowcandle** [comment]
looks fine to me, except the missing whitespace between the number and bytes.

**Comment by mellowcandle** [comment]
what troubles you?

**Comment by rfs613** [comment]
Not the OP here, but my $0.02:

1) the label "Size" is somewhat confusing. Until I put in a larger value, I thought this was the number of bytes needed to store the value. So for example I would expect it to print "Size: 1byte" for an value less than 256. Only after putting in a larger number, did I realize what this field is actually reporting. 

2) consider changing "bytes" to " B" (with a space in front). This would make it more consistent with the other larger units like KiB, MiB, etc.

**Comment by mellowcandle** [comment]
oh. now I see. I'm not sure this will solve the ambiguity either. perhaps I should only print it if it's bigger than 1k

**Comment by rfs613** [comment]
Perhaps change "Size:" to "Human:", and drop "bytes" suffix entirely. That's how "ls -lh" seems to behave.

**Comment by mellowcandle** [comment]
@rfs613 I thing it's a good idea. I'll fix it.
