### ISSUE TITLE
wrong output on overflow

### ISSUE THREAD

**Issue by kilobyte** [mellowcandle/bitwise#26]
In the interactive mode, if the input value doesn't fit in chosen word length, instead of returning an error or truncating, *bitwise* displays a bogus value.

For example, on the first try, I did not notice the 32-bit limitation and typed in `4294967296`.  I'd expect one of:
 * 0
 * "error" or "overflow"
 * extending the field

yet I got:

    hex 19999999
    oct 3146314631
    bin 0 0 0 1 1 0 0 1 | 1 0 0 1 1 0 0 1 | 1 0 0 1 1 0 0 1 | 1 0 0 1 1 0 0 1

**Comment by mellowcandle** [comment]
thanks. I'll try to recreate. on which version are you running?

**Comment by kilobyte** [comment]
v0.32, exact tag (without four later commits, which seem irrelevant).  Debian amd64.
