### ISSUE TITLE
Unable to fill last 4 bits in 64bit mode with decimal, hex or octal fields 

### ISSUE THREAD

**Issue by kavu** [mellowcandle/bitwise#27]
Hi! 

As issue title says — I am unable to fill all bits, when I am filling in decimal, hex or octal fields.

The case:
1. I enter hex `ffff ffff ffff fff`, only 15 symbols (whitespaces are for readability);
2. Bits are `0 0 0 0 1 1 1 1 | 1 1 1 1 1 1 1 1 | 1 1 1 1 1 1 1 1 | 1 1 1 1 1 1 1 1 | 1 1 1 1 1 1 1 1 | 1 1 1 1 1 1 1 1 | 1 1 1 1 1 1 1 1 | 1 1 1 1 1 1 1 1`, decimal is `1152921504606846975`, octal - `77777777777777777777`;
3. I enter 16th `f` to fill bits 60-63, but nothing happens. If I want to delete this last 16th `f` I will delete both 16th and 15th.
4. When I go to the bits field and set all 60-63 bits manually I get decimal to `18446744073709551615`, hex to `ffff ffff ffff ffff`, octal `1777777777777777777777`, all bits are set. And now all values have their expected values.

Is it a bug or expected behaviour?

**Comment by mellowcandle** [comment]
Which version are you using ?
Where did you insert the hex value, in interactive mode ?

**Comment by kavu** [comment]
Both `master` and 0.32 (my own Homebrew formula).

Of course I enter `F`'s in hex field. I recorded a asciicast for you. It differs from what I described above (damn!), but still behaves a little buggy for me: https://asciinema.org/a/hFSqHLh0EPfNTS7MYuGFjz0qM

**Comment by mellowcandle** [comment]
Thanks, I managed to recreate. I'll handle.
Thanks for reporting.
