### ISSUE TITLE
Screen repaint hides decimal, hex and octal fields values

### ISSUE THREAD

**Issue by kavu** [mellowcandle/bitwise#29]
**Describe the bug**
There is a visual bug caused by, I suppose, by `unpaint_screen(); ... paint_screen();`. When the cursor is on the bit-field and I preess `~` NOT hotkey, for example, values of decimal, hex and octal are hidden. And they will update again only when we change the value of bits or move cursor to the up to that fields.

**To Reproduce**
1. Open `bitwise` in interactive mode
2. Enter any number in `decimal` field
3. Move cursor to bitfield
4. Press `~` hotkey
5. Values in decimal, hex and octal are disappeared; label with bit number is also disappeared.
6. Move to up to decimal field - values will appear again, move back to bitsfield - bit label number will appear again.

**Expected behavior**
Screen repaint should update fields to actual current values — values in decimal, hex, octal and bit number should not disappear.

**Screenshots**
https://asciinema.org/a/LMDk8RuDmdqlahkitRvKHPbUX

**Version:**
  - master
  - 0.32

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4

**Comment by mellowcandle** [comment]
Managed to reproduce. Thanks. I'm on it.
