### ISSUE TITLE
Update v0.40 in Macports / Brew

### ISSUE THREAD

**Issue by mellowcandle** [mellowcandle/bitwise#36]
Hey @herrbischoff , @kavu 

Just drafter new release, can you update the packages in Brew / Macports ?

Thanks !

Ramon.

**Comment by herrbischoff** [comment]
https://github.com/macports/macports-ports/pull/4999

**Comment by kavu** [comment]
@chenrui333 already done it 😄 
https://github.com/Homebrew/homebrew-core/pull/43008

**Comment by herrbischoff** [comment]
We’re both so crazy fast… 😁

**Comment by mellowcandle** [comment]
Awesome guys.
How do you want to handle it in the future, opening an Issue like this is suitable ?

**Comment by kavu** [comment]
@mellowcandle I am fine with it. It's not that hard for me, especially when somebody is ahead of me 😁

**Comment by herrbischoff** [comment]
This works very well for me. If I get a notification, I'm usually able
to react quickly. Updating and testing is just a couple minutes worth of work.

**Comment by kavu** [comment]
@mellowcandle both MacPorts and Homebrew are merged!
