### ISSUE TITLE
Update v0.41 in Macports / Brew

### ISSUE THREAD

**Issue by mellowcandle** [mellowcandle/bitwise#41]
Hey @herrbischoff , @kavu

Just drafter new release, can you update the packages in Brew / Macports ?

Thanks !

Ramon.

**Comment by herrbischoff** [comment]
Thanks for the notice. Due to the way MacPorts is managed (and the fact that it breaks down with every new OS release), I gave up on contributing and went with Homebrew. I’ll happily take a look at updating the formula should @kavu be too busy.

**Comment by kavu** [comment]
@herrbischoff Yeah, feel free to catch it up. I'll cover us next time :)

**Comment by kavu** [comment]
As far as I see 0.41 is happily landed in Homebrew https://github.com/Homebrew/homebrew-core/blob/master/Formula/bitwise.rb

**Comment by mellowcandle** [comment]
nice. thanks.
