### ISSUE TITLE
Dividing by 0 is not handled

### ISSUE THREAD

**Issue by VegaDeftwing** [mellowcandle/bitwise#61]
**Describe the bug**
Dividing by 0 causes the program to crash with `Floating point exception (core dumped) ` error.

**To Reproduce**
Divide any number by 0.

**Expected behavior**
It should be handled by printing a warning.

**Version:**
 v0.40

**Desktop:**
 - OS: Ubuntu 20.04

**Comment by mellowcandle** [comment]
[Fixed ](https://github.com/mellowcandle/bitwise/commit/5bb7d300b32bf0eb3925e57f0f8f8a342817fd63)
