### ISSUE TITLE
Add ASCII support

### ISSUE THREAD

**Issue by elig0n** [mellowcandle/bitwise#8]
For hex values that are in range

**Comment by mellowcandle** [comment]
Done:
8d1a6c48fad58b61443ef24e692b47dacddbf4b0

Thanks, I was planning to add this but it slipped out of my mind.

**Comment by elig0n** [comment]
This is good for one character but not for strings. Any chance to implement it for strings ?

**Comment by mellowcandle** [comment]
This should do the trick.
7128ebc7da2e6d159e932266ddfbac671a1cc646
Regarding ncurses, I'll get to that, I have few things I want to do before.
