### ISSUE TITLE
Wrong bits displayed in interactive mode

### ISSUE THREAD

**Issue by noerw** [mellowcandle/bitwise#9]
The displayed bit string is always lagging one input behind.

Steps to reproduce:
- `./bootstrap.sh && ./configure && make && ./bitwise`
- Type `1` (in the Decimal input)
- Observe how the bit string stays all zero
- Type Backspace
- Observe how the bit string displays 1.

On  `v0.30` and on current master (306e66bc3586134f14ac90f2d9256d82e6617240).

**Comment by mellowcandle** [comment]
hmmm... it appears that you're right. I'll fix it soon

**Comment by mellowcandle** [comment]
Fixed:
240c2485ca81ff2b7529cd28d814d1d8c73fc6d8

**Comment by noerw** [comment]
Thanks!
However, now it's still lagging behind when pressing backspace 🤔

**Comment by mellowcandle** [comment]
Yep, missed that spot. just pushed a fix for that as well.
0fff214a7a5e44a628e3d1595a9ca379bd40de33

**Comment by mellowcandle** [comment]
Thanks for the sharp eye for details :)
